ic-hep/pdm

.travis.yml, setup.py, src/pdm/__init__.py, src/pdm/utils/__init__.py, test/pdm/test_dummy.py, tox.ini
=> Add template files

src/pdm/utils/config.py, src/pdm/utils/singleton.py, test/pdm/utils/test_config.py, test/pdm/utils/test_singleton.py
@sfayer I think this is good now. Please review.
=> Adding ConfigSystem and singleton decorator.

src/pdm/utils/__init__.py, src/pdm/utils/daemon.py, src/pdm/utils/lockfile.py
=> Daemon util

etc/build_ca.sh, etc/openssl.cnf, src/pdm/demo/DemoService.py, src/pdm/framework/Database.py, src/pdm/framework/FlaskWrapper.py, tox.ini
Here are some patches to get the code working correctly on EL7 nodes with older versions of things.
=> EL7 fixups

src/pdm/framework/FlaskWrapper.py, test/pdm/demo/test_DemoService.py
This adds an example of how to do service testing within the framework. Hopefully I can write something similar for client testing, although that's proving to be a bit more complicated.
=> Add DemoService tests (and testing framework)

src/pdm/demo/DemoService.py, src/pdm/framework/Database.py
including datetime for timestamps.
=> Use Dedicated JSON encoder for table types

src/pdm/utils/hashing.py, test/pdm/utils/test_hashing.py
Add a password hashing util library + test cases.
=> Add util hashing library

test/pdm/utils/test_config.py, test/pdm/utils/test_db.py
Add/improve tests for a couple of utils modules to increase test coverage.
=> Improve test coverage

src/pdm/utils/sshkey.py, test/pdm/utils/test_sshkey.py
Adds a tool set for generating SSH keys (will mainly be used within cred_service).
=> Add basic SSH key utils + tests

src/pdm/demo/DemoClient.py, src/pdm/framework/FlaskWrapper.py, src/pdm/framework/RESTClient.py, src/pdm/framework/Startup.py, test/pdm/demo/test_DemoClient.py, test/pdm/demo/test_DemoService.py
Update the framework RESTClient to allow "serverless" testing and add an example of doing this to the DemoClient.
=> Demo client test

src/pdm/framework/WSGIServer.py, test/pdm/framework/test_WSGIServer.py
More boring unit tests I'm afraid... Plus a bug fix for the __dn_to_str function that was found by writing the tests :-)
=> Add test units for WSGIServer module

bin/test_demo.py, etc/demo.auth, etc/demo.conf, src/pdm/demo/DemoClient.py, src/pdm/demo/DemoService.py, src/pdm/framework/RESTClient.py, test/pdm/demo/test_DemoClient.py, test/pdm/demo/test_DemoService.py
Adding the put operation to framework.RESTClient and updated the turtle demo, so turtles can now be modified. 
Still to be done:
- in src/pdm/framework/RESTClient.py, the RESTClientTest class needs a matching put method.
- in test/pdm/demo/test_DemoClient.py, add a test for the new DemoService function, to get the coverage back up to 100%.
Tests added.
=> Janusz add put

src/pdm/framework/RESTClient.py, test/pdm/framework/test_RESTClient.py
Yet another boring test class for the two classes in RESTClient.
=> RESTClient unit tests

src/pdm/demo/DemoClient.py, src/pdm/demo/DemoDB.py, src/pdm/demo/DemoService.py
Yep, instead of doing anything useful for the last 20 minutes, I decided to improve the pylint score of the demo (mainly as it was still using the 2-space indentation).
At some point I'm considering adding a pylint test to the CI suite, but that will mean doing something about all of the "db" and "Tablename" style variables which don't meet the usual expected pattern (adding a pylint comment to everyone is too onerous, but making it more broad generally also isn't ideal).
=> Pylint demo components

.pylintrc, src/pdm/framework/Database.py, src/pdm/framework/FlaskWrapper.py, src/pdm/framework/RESTClient.py, src/pdm/framework/Startup.py, src/pdm/framework/Tokens.py, src/pdm/framework/WSGIServer.py, src/pdm/utils/X509.py, src/pdm/utils/__init__.py, src/pdm/utils/config.py, src/pdm/utils/daemon.py, test/bin/run_pylint.sh
This tidies up all pylint warnings in current master (other than TODO entries) and increases the required score to 9.
=> More pylint fixes

.gitignore, .pylintrc, etc/system.auth, etc/system.conf, src/pdm/cred/CredClient.py, src/pdm/cred/CredDB.py, src/pdm/cred/CredService.py, src/pdm/cred/__init__.py, src/pdm/framework/FlaskWrapper.py, src/pdm/utils/X509.py, src/pdm/utils/sshkey.py, test/pdm/cred/test_CredClient.py, test/pdm/cred/test_CredService.py, test/pdm/utils/test_X509.py
This adds an initial implementation of the online CA for the project (aka the credential service)... There are a few TODOs left to deal with, but the basic interface won't change.
There are also a couple of other minor changes which got rolled in as I was working on it (like adjusting pylint to cope with DB table names that have more than one capital letter).
=> Add Credential service

MANIFEST.in, etc/demo.auth, etc/demo.conf, setup.py, src/pdm/demo/DemoService.py, src/pdm/demo/static/turtles.css, src/pdm/demo/templates/turtles.html, src/pdm/framework/FlaskWrapper.py, src/pdm/framework/Startup.py, test/pdm/demo/test_DemoService.py
Adds a web-page support + demo so that we can use the same framework for the user frontend.
=> Add web-page support + demo + test

src/pdm/utils/hashing.py, test/pdm/utils/test_hashing.py
This may be needed to generate a user specific key.
=> Add option for fixed salt in hashing mod

src/pdm/utils/X509.py, test/pdm/utils/test_X509.py
This completes all TODOs in the X509 module and gets the test coverage back to 100%.
=> Fix all X509 todos

src/pdm/utils/sshkey.py, test/pdm/utils/test_sshkey.py
Simply adds one missing test case.
=> Fix remaining todo in sshkey module

doc/source/reference/api/siteservice.rst, etc/system.auth, etc/system.conf, src/pdm/endpoint/EndpointClient.py, src/pdm/endpoint/EndpointDB.py, src/pdm/endpoint/EndpointService.py, src/pdm/endpoint/__init__.py, test/pdm/endpoint/test_EndpointClient.py, test/pdm/endpoint/test_EndpointService.py
This adds the endpoint service + client + tests as per the spec I committed earlier in the week.
Actually starting the full server with multiple classes/services loaded doesn't work yet, but that fix belongs in a different pull request.
=> Add endpoint service

src/pdm/framework/RESTClient.py
Just added requests.codes.accepted to a tuple of non error codes.
=>  allow return code 201 to be accepted as well as OK by the RESTClient

src/pdm/framework/RESTClient.py, src/pdm/framework/Tokens.py, test/pdm/framework/test_RESTClient.py, test/pdm/framework/test_Tokens.py
=> Add method for unpacking tokens

src/pdm/endpoint/EndpointService.py, src/pdm/utils/db.py, test/pdm/endpoint/test_EndpointService.py, test/pdm/utils/test_db.py
(cherry picked from commit 3a7297566c8e11d8b5cf543427d41118e6f7ffce)
@sfayer I broke out the db.py changes by creating a roll back commit on the workqueue branch and then applying the patch as a separate commit on that branch which I cherry pick for you here. This I think should allow you to merge this separately without messing up Janusz with a rebase.
=> Make managed_session more flexible.

src/pdm/framework/FlaskWrapper.py
When starting lots of modules, the previous code would use function names as unique identifiers... Quite frequently this would not work: At least two modules have functions named "add_user".
This patch appends the full class name onto the endpoint which keeps them all unique. Fixes #50.
=> Prevent namespace conflicts between modules

src/pdm/userservicedesk/HRService.py, test/pdm/userservicedesk/test_HRClient.py, test/pdm/userservicedesk/test_HRService.py
Hi Janusz,
I didn't see a pull request for doing this, so I wrote one myself for you to approve... It turns out it's really easy to replace a class with patch.
There are still some other bugs that prevent full integration from working yet... I'll submit patches for that soon.
Regards,
Simon
=> Switch user service to use real cred client

src/pdm/endpoint/EndpointService.py
=> Fixed for endpoint test data

src/pdm/framework/FlaskWrapper.py
This request adds basic access logging to the server log: This makes debugging problems _much_ easier. Each request is also assigned a UUID, the eventual aim is that any user-facing error can contain the UUID of the request that failed, to make tracking it down in the log much easier.
=> Add access log & improved 404 handling

src/pdm/cred/CredService.py
Use managed_session wherever possible in CredService to make sure it correctly recovers from database errors.
Closes #60.
=> Improve CredService database safety

src/pdm/userservicedesk/HRService.py, test/pdm/userservicedesk/test_HRClient.py, test/pdm/userservicedesk/test_HRService.py
Modified various HTTP return codes in HRService. Restrict 403 to login failures etc.
=>  Fix (hopefully) https return codes

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueClient.py, src/pdm/workqueue/WorkqueueDB.py, src/pdm/workqueue/WorkqueueService.py, test/pdm/workqueue/test_Worker.py
fixes PEP8 and pylint violations. Also introduces the test_Worker.py file albeit with tests disabled at this point as I still need to get them working.
=> Workqueue updates

bin/pdm, etc/system.auth, etc/system.client.conf
Just minor bugs where things didn't quite work after all of today's merges....
=> Misc fixes for integration testing

src/pdm/framework/Database.py, src/pdm/framework/FlaskWrapper.py, test/pdm/framework/test_Database.py
It turns out there were no where near as many typos as I thought... Only one class.
Closes #92.
=> Fix SQAlchemy typo

src/pdm/CLI/user_subcommand.py, src/pdm/cred/CredService.py
A very tiny amount of pylint fixes, I hoped to to more, but more of the remainder are fairly complicated for various reasons.
=> Misc pylint fixes

src/pdm/utils/hashing.py
This adds a get_salt function to hashing so that if we ever need to change how the salting works, it can be done in one place. This is mainly for #78 to use.
=> Break out get_salt function

.pylintrc, src/pdm/cred/CredService.py, src/pdm/endpoint/EndpointService.py, src/pdm/userservicedesk/HRService.py, src/pdm/utils/config.py, src/pdm/utils/daemon.py, src/pdm/utils/db.py
=> Globally disable broad-excepts

src/pdm/workqueue/WorkqueueClient.py
this fixes https://github.com/ic-hep/pdm/issues/87
=> Fix for double decoding JSON data from RESTClient vs FlaskClient.

src/pdm/workqueue/WorkqueueService.py
this PR enables you to create the enums with either lower or upper case keywords. It also handles better the case when enum creation fails returning a proper HTTP error 400 bad request.
=> Case insensitive enums

src/pdm/framework/FlaskWrapper.py, src/pdm/framework/RESTClient.py, test/pdm/cred/test_CredService.py, test/pdm/demo/test_DemoService.py, test/pdm/endpoint/test_EndpointService.py, test/pdm/framework/test_RESTClient.py, test/pdm/userservicedesk/test_HRService.py, test/pdm/workqueue/test_WorkqueueService.py
Hi Alex,
Here is my suggested solution to #104... Just a wrapper to FlaskClient to make it behave more like RESTClient... I'm not sure about decoding the return values too, so it's probably not complete yet, but it's most of the way there.
Regards,
Simon
=> Flask test client fix

bin/start_worker.py, etc/build_ca.sh, etc/system.auth, etc/system.worker.conf, src/pdm/workqueue/Worker.py
fixes https://github.com/ic-hep/pdm/issues/106
=> Adding Worker startup script.

src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/111
=> Fix shell path sanitisation in WorkqueueService.

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py, src/pdm/userservicedesk/TransferClientFacade.py, test/pdm/CLI/test_usercommand.py
Added output handling to CLI list
=> Janusz siteformat fix

src/pdm/workqueue/WorkqueueService.py
This commit fixes https://github.com/ic-hep/pdm/issues/64.
=> Properly pop config params in a startup method.

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py, test/pdm/CLI/test_usercommand.py
Call job status properly rather than resubmitting list jobs ...
=>  fix job ststus call

src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/122.
@sfayer this is a quick and dirty fix in the last 5 mins and it's possible I'll need to fix the parsing again but in my local (albeit limited) testing it removes lines starting with + and also trailing tabs. 
please test it and merge if happy
=> Fix parsing of set -x lines and trailing tab characters.

src/pdm/framework/RESTClient.py, test/pdm/framework/test_RESTClient.py
=> Catch requests errors in RESTClient

src/pdm/cred/CredService.py, src/pdm/endpoint/EndpointService.py
=> Better log messages in cred and endpoint services

src/pdm/CLI/user_subcommand.py, test/pdm/CLI/test_usercommand.py
Now available:
1) site listing
2) copying with current status or status monitoring (-b option)
3) removing with current status or status monitoring (-b option)
4) status with or w/o the -b option
=> Janusz cli status updt

src/pdm/cred/CredService.py, src/pdm/utils/X509.py, test/pdm/cred/test_CredService.py, test/pdm/utils/test_X509.py
Adds a DN normalisation function and calls it in most places where a user supplied DN is processed.
This is only partially covers #65... The rest of that ticket will be handled in the patch for #68.
=> Normalise DNs in some places

src/pdm/endpoint/EndpointService.py, test/pdm/endpoint/test_EndpointClient.py, test/pdm/endpoint/test_EndpointService.py
Check that endpoint URLs look about right when they're added to the endpoint service.
Closes #136.
=> Endpoint url check

src/pdm/workqueue/Worker.py
@sfayer as discussed before I'm reverting the generator expressions in the Worker
=> Reinstate worker generator expressions.

src/pdm/workqueue/Worker.py
This fixes https://github.com/ic-hep/pdm/issues/134
=> Worker remove job credentials when done.

etc/system.auth, src/pdm/framework/FlaskWrapper.py, src/pdm/workqueue/WorkqueueService.py, test/pdm/workqueue/test_WorkqueueService.py
This fixes issue https://github.com/ic-hep/pdm/issues/126.
modified:   src/pdm/framework/FlaskWrapper.py
modified:   src/pdm/workqueue/WorkqueueService.py
modified:   test/pdm/workqueue/test_WorkqueueService.py
=> Adding ability to get individual attempts logs.

etc/system.auth
Simple fix to the auth file...
=> Allow worker to delete proxy

src/pdm/cred/CredService.py, src/pdm/demo/DemoService.py, src/pdm/endpoint/EndpointService.py, src/pdm/framework/Decorators.py, src/pdm/framework/FlaskWrapper.py, src/pdm/userservicedesk/HRService.py, src/pdm/web/WebPageService.py, src/pdm/workqueue/WorkqueueService.py, test/pdm/framework/test_Decorators.py
As discussed... Moves the decorators into their own module and adds tests.
=> Move decorators into their own module

src/pdm/workqueue/Worker.py
This fixes https://github.com/ic-hep/pdm/issues/152#event-1541217041
=> Add inter-poll sleep for server errors as well as just no work.

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/153
This PR also includes a refactoring of the Worker.
=> Worker deletes user credentials when it's the last attempt.

src/pdm/workqueue/WorkqueueService.py
Fixes https://github.com/ic-hep/pdm/issues/127
=> Allow shell paths begining with ~

src/pdm/userservicedesk/HRService.py, src/pdm/userservicedesk/models.py
#closes #99 closes #137 forever ;-)
=>  address issues #99 and #137

src/pdm/workqueue/Worker.py
This fixes https://github.com/ic-hep/pdm/issues/112
=> Increasing the logging verbosity of the Worker.

src/pdm/workqueue/WorkqueueDB.py, src/pdm/workqueue/scripts/dummy.sh
This commit fixes https://github.com/ic-hep/pdm/issues/63
=> Add dummy protocol for testing.

src/pdm/demo/DemoService.py, src/pdm/framework/ACLManager.py, src/pdm/framework/Decorators.py, src/pdm/framework/FlaskWrapper.py, src/pdm/framework/RESTClient.py, src/pdm/framework/Startup.py, src/pdm/utils/hashing.py
Fixes for pylint day... Part of #169.
=> Pylint fixes

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py
=> Janusz cli protocol opt

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueService.py, src/pdm/workqueue/__init__.py
Part of https://github.com/ic-hep/pdm/issues/169. Brings the Workqueue package score to 10.
modified:   src/pdm/workqueue/Worker.py
modified:   src/pdm/workqueue/WorkqueueService.py
modified:   src/pdm/workqueue/__init__.py
=> Fix some pylint violations.

src/pdm/userservicedesk/TransferClientFacade.py
an unimportant change in an unimportant method ;-)
=> small pylint fix

src/pdm/CLI/pdmcli.py, src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py
CLI: added a config file search hierarchy.
=> Janusz cli config

src/pdm/framework/ACLManager.py, test/pdm/framework/test_ACLManager.py
This patch looks for the expiry of tokens in the main framework service. If a token contains a dict with an expiry entry, it's automatically checked by the framework.
Closes #202.
=> Add token expiry to ACLManager

MANIFEST.in, etc/system.auth, src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueClient.py, src/pdm/workqueue/WorkqueueDB.py, src/pdm/workqueue/WorkqueueService.py, src/pdm/workqueue/scripts/dummy.sh, test/pdm/workqueue/test_Worker.py, test/pdm/workqueue/test_WorkqueueClient.py, test/pdm/workqueue/test_WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/199
=> Job elements

src/pdm/web/WebPageService.py, test/pdm/web/test_WebPageService.py
=> change web to SiteService

etc/system.client.conf, etc/system.server.conf, etc/system.worker.conf
I missed another reference to the old services: the config files :-)
=> Fix services + ports in default config

bin/start_worker.py
This fixes https://github.com/ic-hep/pdm/issues/213
=> Fix argument passed to Worker in bin/start_worker.py.

etc/system.server.conf
Oops, forgot to remove an unused option...
=> Fix config again

src/pdm/CLI/user_subcommand.py, src/pdm/workqueue/scripts/pdm_gfal2_ls.py, test/pdm/CLI/test_usercommand.py
This is agreed with Alex. He has to modify his list client to accept an extra parameter(s).
=>  add listing depth to the CLI, one level is the default (CLI-side)

src/pdm/workqueue/WorkqueueClient.py
This fixes https://github.com/ic-hep/pdm/issues/227 and is related to https://github.com/ic-hep/pdm/issues/223
=> Pass extra options from WorkqueueClient to worker scripts.

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/226
=> Pass dir list to pdm_gfal2_rm.py separate from file list.

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py, test/pdm/CLI/test_usercommand.py, test/pdm/userservicedesk/test_TransferClient.py
Add site logoff and various CLI improvements. Fixes #237 #240 
Correct the listing key (#240)
=>  addresses #237 and #240

src/pdm/CLI/user_subcommand.py
=> stop listing follow directories, if not recursive

src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/256
HOPEFULLY :wink: 
@sfayer note can you please try running COPY jobs again as this PR refactors and fixes some problems we hadn't yet discovered.
=> Refactor service handling of worker output.

src/pdm/workqueue/WorkqueueService.py
hopefully fixes https://github.com/ic-hep/pdm/issues/259
=> Fixes for destination path and job index in COPY/REMOVE jobs.

src/pdm/workqueue/Worker.py
addresses https://github.com/ic-hep/pdm/issues/259.
=> Fix for non-existing dirs key in worker data.

src/pdm/workqueue/scripts/pdm_gfal2_copy.py, src/pdm/workqueue/scripts/pdm_gfal2_ls.py, src/pdm/workqueue/scripts/pdm_gfal2_rm.py
This PR goes hand in hand with #272
=> Janusz fix gfal rm

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueService.py
PR also cleans up a split import.
=> Add config option for worker to request new job splitting algorithm.

src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueDB.py, test/pdm/workqueue/test_WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/274
=> Don't pass COPY/REMOVE job extra_opts to the LIST element 0.

src/pdm/workqueue/scripts/pdm_gfal2_ls.py
Add a 'forgotten' helpr call for pdm_gfal2_ls json_input()
=> Janusz gfal helper fix2

src/pdm/CLI/user_subcommand.py
No aliases yet, but modify the login command to ask for an email address.
=> login: ask for an email address when not provided with the -e option

etc/system.client.conf, src/pdm/utils/myproxy.py, src/pdm/workqueue/Worker.py, test/pdm/utils/test_myproxy.py
This fixes the VOMS support in the myproxy module to the point that it actually all works and I can list files on our grid storage.
Fixes #284 and fixes #285.
=> Myproxy VOMS fix

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/HRService.py, src/pdm/userservicedesk/HRUtils.py, test/pdm/userservicedesk/test_HRUtils.py
Added functionality as described in #286. Fixes #286.
=>  get username from toke when logging in, if available

src/pdm/installer/install_pdm.py
=> Check for gridmap myproxy callout

setup.py
=> Add enum34 requirement

etc/system.auth, src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueClient.py, src/pdm/workqueue/WorkqueueDB.py, src/pdm/workqueue/WorkqueueService.py
Fixes https://github.com/ic-hep/pdm/issues/281
=> Adding new RENAME/MKDIR Job types.

src/pdm/workqueue/scripts/pdm_gfal2_copy.py
=> fix line 66, for loop

src/pdm/workqueue/scripts/pdm_gfal2_chmod.py, src/pdm/workqueue/scripts/pdm_gfal2_mkdir.py, src/pdm/workqueue/scripts/pdm_gfal2_rename.py, src/pdm/workqueue/scripts/pdm_gfal2_rm.py
gfal back-end for mkdir and rename
=> Janusz gfal mkdir rename

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClient.py
Add user jobs command. Still need to resolve the site_id and user_id. Still useful for Alex in his Web work.
=> Janusz jobs

src/pdm/userservicedesk/TransferClient.py
job elements client operation for Alex.
=> Janusz job elements

src/pdm/CLI/pdmcli.py, src/pdm/CLI/user_subcommand.py
Add site name to jobs listing table, simplify table printing code, set requests logger level to WARNING.
=> Janusz jobs mk3

src/pdm/CLI/user_subcommand.py
=> the jobs table header now shows site name rather than id

src/pdm/workqueue/WorkqueueService.py
This is useful for the web app which needs to create progress bars.
modified:   src/pdm/workqueue/WorkqueueService.py
=> Return element status statistics with all user jobs.

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/TransferClientFacade.py, test/pdm/CLI/test_usercommand.py
=> add check for site login session for relevant CLI commands

doc/source/reference/api/pdm.CLI.rst, doc/source/reference/api/pdm.userservicedesk.rst, src/pdm/userservicedesk/HRClient.py, src/pdm/userservicedesk/HRService.py, src/pdm/userservicedesk/HRUtils.py, src/pdm/userservicedesk/TransferClient.py, src/pdm/userservicedesk/TransferClientFacade.py
No change in the code, only docs updates
=> Janusz apidocs

doc/source/reference/api/pdm.CLI.rst, src/pdm/CLI/pdmcli.py, src/pdm/CLI/user_subcommand.py
Revised documentation for the CLI modues.
=>  review the docs for the CLI modules

src/pdm/web/templates/registration.html
This patch fixes https://github.com/ic-hep/pdm/issues/325
=> Adding + symbol to the client side registration email filter regex.

src/pdm/web/WebPageService.py
This patch fixes https://github.com/ic-hep/pdm/issues/326
=> Fix typo in sign up redirect.

src/pdm/web/templates/loginform.html
This fixes https://github.com/ic-hep/pdm/issues/327
=> Change sitelogin username placeholder text: email->username

src/pdm/web/templates/dashboard.html
This patch fixes https://github.com/ic-hep/pdm/issues/329
=> Stop the sliding up/down of the navigation bar.

src/pdm/web/WebPageService.py, src/pdm/web/templates/datamover.html
This patch fixes https://github.com/ic-hep/pdm/issues/339
=> Fix the broken logout flash message.

src/pdm/web/templates/dashboard.html
This patch also removes the backspace as a trigger for delete jobs.
fixes https://github.com/ic-hep/pdm/issues/341
=> Stop the backspce/del key triggering delete job when text entry focus

etc/system.auth, src/pdm/framework/ACLManager.py
This might be the fix for #258, it'll need testing...
=> Add auth entry to allow user to delete all their own sites

src/pdm/CLI/user_subcommand.py, src/pdm/userservicedesk/HRService.py
tests now pass with the request.raw_token in the mock.
=> Janusz user unregister

src/pdm/workqueue/Worker.py
This patch fixes https://github.com/ic-hep/pdm/issues/357
=> Fix Worker cadir bug.

etc/system.auth, src/pdm/web/templates/joblist.html, src/pdm/workqueue/Worker.py, src/pdm/workqueue/WorkqueueDB.py, src/pdm/workqueue/WorkqueueService.py, test/pdm/workqueue/test_WorkqueueService.py
=> Workqueue monitoring info

src/pdm/workqueue/scripts/pdm_gfal2_copy.py
Tested with Alex's origin/workqueue_monitoring_info
=> modify gfal callbacks. They are jobid-aware and dump json to stdut

src/pdm/web/templates/dashboard.html
This patch fixes https://github.com/ic-hep/pdm/issues/340
=> Add a directory up ".." folder icon at the top of listings.

etc/system.auth, src/pdm/web/WebPageService.py, src/pdm/web/templates/joblist.html, src/pdm/web/templates/output_carousel.html
This patch adds the ability to view the output log file from each attempt for a given job element.
=> Add popup job output with all attempts.

src/pdm/workqueue/Worker.py
This commit addresses part 2 of https://github.com/ic-hep/pdm/issues/343
=> Adding a timeout to the worker.

src/pdm/workqueue/WorkqueueService.py
=> Fix the logic when looking for attempt log.

src/pdm/installer/README.md, src/pdm/installer/install_pdm.py
Results from the first pass at installing an endpoint.
=> more details for installation

src/pdm/installer/install_pdm.py
=> Remove double / if present in service_url

src/pdm/installer/install_pdm.py
=> Strip quotes around string options in installer

doc/source/server/install.rst
Just a start of adding some new documentation sections...
=> Add placeholder for server documentation

src/pdm/installer/install_pdm.py
=> Replace double slashes in installed URL more carefully

src/pdm/web/templates/dashboard.html, src/pdm/web/templates/newjob.html
=> added alt text to buttons

src/pdm/CLI/user_subcommand.py, src/pdm/workqueue/scripts/pdm_gfal2_chmod.py, src/pdm/workqueue/scripts/pdm_gfal2_ls.py, src/pdm/workqueue/scripts/pdm_gfal2_mkdir.py, src/pdm/workqueue/scripts/pdm_gfal2_rename.py, src/pdm/workqueue/scripts/pdm_gfal2_rm.py
* add global (CORE) gfal timeout to all gfal scripts
* add a client-site timeout for listing.
=> Janusz gfal core timeout

src/pdm/web/templates/datamover.html
This fixes https://github.com/ic-hep/pdm/issues/382
=> Fix GDRP dismiss button text.

src/pdm/web/templates/dashboard.html
This fixes https://github.com/ic-hep/pdm/issues/397
=> Condense the endpoint directory listing.

src/pdm/web/templates/dashboard.html
This fixes https://github.com/ic-hep/pdm/issues/390
=> Add filesizes to endpoint listings.

src/pdm/web/templates/joblist.html
fixes https://github.com/ic-hep/pdm/issues/400
=> Fix size units for transfered amounts.

src/pdm/web/templates/dashboard.html
This patch fixes https://github.com/ic-hep/pdm/issues/406
=> Select a range of endpoint listing entries using Shift key.

src/pdm/web/WebPageService.py, src/pdm/web/templates/dashboard.html, src/pdm/web/templates/newjob.html
fixes https://github.com/ic-hep/pdm/issues/392
=> Webapp copy overwrite

src/pdm/web/templates/dashboard.html
This fixes https://github.com/ic-hep/pdm/issues/407
=> When first listing a site, navigate to def_path.

src/pdm/workqueue/scripts/pdm_gfal2_copy.py
Calculate elapsed time when monitoring is not available for a given copy job.
=> add manual monitoring in a case when callbacks are not fired by gfal

src/pdm/web/templates/dashboard.html, src/pdm/web/templates/joblist.html, src/pdm/workqueue/WorkqueueService.py
This PR works in coordination with https://github.com/ic-hep/pdm/pull/425 to pick up the pseudo monitoring entry for small files. They should therefore be merged together.
It also contains some a unified/ smart way of reporting file sizes/ transfer amounts/rates that scale with the quantity to ensure they look good when printed on the UI
=> Workqueue small file monitoring

src/pdm/CLI/user_subcommand.py
=> fix user swap (#434)

src/pdm/installer/install_pdm.py
=> Change return code for install_pdm.py -w

src/pdm/web/WebPageService.py, src/pdm/web/templates/dashboard.html
There is concern about Gravatar possibly creating shadow profiles about users. This PR give the option to disable the use of Gravatar. This PR fixes https://github.com/ic-hep/pdm/issues/429
@sfayer the name of the config entry is up for discussion. But this is the basic fix.
=> Make Gravatar optional.

etc/system.auth, src/pdm/userservicedesk/HRClient.py, src/pdm/userservicedesk/HRService.py, src/pdm/web/WebPageService.py, src/pdm/web/templates/verification.html
This PR fixes https://github.com/ic-hep/pdm/issues/428
=> Email verify

src/pdm/workqueue/WorkqueueService.py, test/pdm/workqueue/test_WorkqueueService.py
Fixes https://github.com/ic-hep/pdm/issues/423
=> Fixing the workqueue by_size algorithm.

src/pdm/web/WebPageService.py, src/pdm/web/templates/loginform.html
It's been a while since I did PDM work but I believe that this relatively simple patch should fix @marianne013 issue. We will probably have to wait until we have the system up and running to confirm this but it's here ready.
This fixes https://github.com/ic-hep/pdm/issues/385
=> Stop Autofilling PDM details into site login
