- tox.ini
This allows for a specific test unit to be run in tox rather than the whole test-suite... This is becoming more important as some of the X509 tests can take a while to run (still only tens of seconds, but long enough to get in the way if you're working on something else).
> Allow parsing args to py.test via tox

- src/pdm/framework/FlaskWrapper.py
- src/pdm/framework/Tokens.py
- test/pdm/framework/test_Tokens.py
Adds a proper set of tests for the framework Tokens module. Also changes the Token interface slightly so that verify errors throw exceptions rather than the weird tuple that was returned before.
> Add test cases for Tokens module

- src/pdm/framework/Database.py
- src/pdm/framework/FlaskWrapper.py
- test/pdm/framework/test_Database.py
Allow database objects to be passed to jsonify.
Add a new (optional) attribute to database objects '__json_fields__' to limit which fields get converted to JSON when .json() or jsonify() is called.
Add test cases for all of the framework.Database classes.
> Database (JSON) improvements

- doc/source/index.rst
- doc/source/reference/api/credservice.rst
Just as a starting point for REST API documentation... This is particularly important for the web interface, which may not be able to use a prebuilt python client class (if we write it in pure javascript).
> Add example REST API documentation for the credential service.

- src/pdm/utils/X509.py
- test/pdm/utils/test_X509.py
I found that the CA code would fail to issue a cert if the CA cert was loaded from a PEM file: This was caused by improper initialisation of __sign_key, this patch fixes the problem and adds a regression test.
> Fix failure to sign certs after reload in X509CA

- etc/demo.auth
- src/pdm/framework/FlaskWrapper.py
Originally you could write a security rule for all methods on an endpoint... Janusz demonstrated that it's too easy to do this for a simple GET endpoint, but later add something like DELETE and have it open to everyone without realising it.
This patch makes it so that anything other than GET must specify the method to be allowed.
I'll write a full spec of the config files (including the auth files) when we concentrate on the user documentation.
> Disable default (methodless) rules for endpoints

- .travis.yml
- src/pdm/framework/RESTClient.py
- test/bin/run_server_test.sh
- tox.ini
This adds support for running the whole demo server & client as a system test along side the unit tests on travis.
I'm not sure we're actually using tox-travis any more, but I'll leave it in for now.
> Run full demo server/client as part of the travis tests

- .pylintrc
- test/bin/run_pylint.sh
- test/pdm/demo/test_DemoClient.py
- test/pdm/demo/test_DemoService.py
- tox.ini
This adds a test environment for pylint, tidies the tox config up a little and pins the test versions to match the EL7 versions (as well as one fix for where __name__ isn't included in the old unittest.TestCase base class for some reason).
I'll probably raise the required pylint score up to 9 once the current code actually reaches that number (I'll do another batch of pylint fixes in the near future, perhaps once I've done more of the actual CredService code).
> Add pylint as a test

- src/pdm/framework/FlaskWrapper.py
- test/pdm/demo/test_DemoService.py
This can be used for testing the contents of tokens returned from services (as now demonstrated in DemoService tests).
> Make token_svc a public attribute of FlaskWrapper

- doc/source/reference/api/siteservice.rst
This adds the basic REST spec for the site/endpoint database. This is used for keeping track of the endpoints and mapping users to local usernames at those sites.
> Add draft plan for new site/endpoint service.

- src/pdm/framework/WSGIServer.py
- test/pdm/cred/test_CredService.py
Sometimes x509name objects have the attributes for all parts of the DN, with missing ones set to None, other times they have the attributes missing completely (depending on the library version).
Older versions of M2Crypto are also less tolerant of unicode strings from the DB.
> Fix test suite for real CentOS7 nodes

- etc/build_ca.sh
- etc/system.auth
- src/pdm/cred/CredDB.py
- src/pdm/demo/DemoService.py
- src/pdm/endpoint/EndpointDB.py
- src/pdm/endpoint/EndpointService.py
- src/pdm/framework/FlaskWrapper.py
- src/pdm/framework/Startup.py
- test/bin/run_server_test.sh
- test/pdm/demo/test_DemoClient.py
- test/pdm/demo/test_DemoService.py
- test/pdm/endpoint/test_EndpointClient.py
- test/pdm/endpoint/test_EndpointService.py
This adds quite a few things:
* Support for starting multiple modules within one service.
* Support for test data (-t option to demo_server.py).
* Root certificate who can do anything on any service (at least in theory, they still need special rules in .auth, there isn't any backdoor in the code for this :-)
Hopefully that's enough to enable one module to be tested against another... You start the both services up together giving the -t option to demo_server.py and then use any client (curl, a custom python client, Janusz's CLI once it exists) to poke things.
Regards,
Simon
> Fix multi-module testing

- .gitignore
As we improve the testing, we will probably eventually want a persistent database... This patch simply ignores that most likely location of that file in the git client.
> ignore test.db file

- src/pdm/framework/FlaskWrapper.py
It was discovered that on some versions of Flask-SQLAlchemy (most notably the version installable on EL7 with yum), the database sometimes has missing tables. This patch fixes that problem by running the __add_tables helper for each class rather than once on start-up.
> Ensure DB tables are added on a class-by-class basis

- src/pdm/framework/RESTClient.py
Conceptually `RESTClientTest` is a `RESTClient`, just one intended for testing. This means that `isinstance(obj, RESTClient)` type checks will pass with `RESTClientTest`. More importantly for me anyway ;-) while the super call in the `__init__` is sufficient for most client testing, if like in `workqueue.Worker` you have multiple inheritance you may want to call the `__init__` directly rather than use some horrible super fudge with variable args passing around. In this case it currently fails to initialise as the base (`RESTClientTest`) is not a `RESTClient`. This passes all my local workqueue testing, lets see what Travis makes of it.
> Make RESTClientTest Inherit from RESTClient

- etc/system.client.conf
- etc/system.server.conf
- src/pdm/endpoint/EndpointService.py
- test/pdm/endpoint/test_EndpointClient.py
- test/pdm/endpoint/test_EndpointService.py
Simple update of endpoint URI to standardise on "endpoint". Closes #71.
> Normalise endpoints -> endpoint in URI

- src/pdm/framework/RESTClient.py
- test/pdm/framework/test_RESTClient.py
Checks for unexpected options in the client config section.
Closes #98.
> Client config check

- src/pdm/framework/RESTClient.py
- test/pdm/framework/test_RESTClient.py
- test/pdm/userservicedesk/test_HRClient.py
Adds an exception class that will allow clients to easily get the error code + message (while still being backwards compatible with old code).
Closes #76.
> Better rest client errors

- bin/test_demo.py
- etc/demo.auth
- etc/system.auth
- src/pdm/cred/CredService.py
- src/pdm/framework/ACLManager.py
- src/pdm/framework/FlaskWrapper.py
- src/pdm/framework/Startup.py
- src/pdm/utils/X509.py
- test/pdm/cred/test_CredService.py
- test/pdm/framework/test_ACLManager.py
- test/pdm/utils/test_X509.py
This moves the access code out of FlaskWrapper into its own class where it can be more readily tested. It changes the auth file format to be more understandable (no more magic for <int> style endpoints) and adds a comprehensive set of tests.
Closes #65. Closes #68.
> Refactor and improve ACL code

- .gitignore
- etc/system.server.conf
- src/pdm/framework/Startup.py
- src/pdm/utils/config.py
This opens the proper log files for each server and sets the level correctly. There is probably a lot more we can improve here (WSGI server specific levels, automatically include client IP in Flask log messages, etc...), but this should be fine for initial testing.
Closes #51.
> Much more sensible logging

- src/pdm/framework/FlaskWrapper.py
- src/pdm/web/WebPageService.py
This moves setting the secret_key for Flask cookies into the main framework... For @marianne013 to test (as there are no unit tests for this module yet ;-)
> Set secret_key in FlaskWrapper

- src/pdm/workqueue/WorkqueueService.py
- test/pdm/workqueue/test_WorkqueueService.py
This is only worker facing changes so doesn't impact the public client API. Makes the service a bit more bulletproof.
> Force required attrs from the Worker client.

- tox.ini
This allows tox to pull in sitepackages from the host machines... While this risks contaminating the test environment, it seems to be the only way to get the dependencies reliably available on older platforms (specifically EL7). As far as I can tell it doesn't currently change the test results on Fedora or Travis, so I think it's OK for now.
(When I say dependencies, it's mainly the ones that rely on compatibility with the host C library, such as M2Crypto and pyOpenSSL).
> Add sitepackages flag to tox for EL7 testing

- src/pdm/CLI/user_subcommand.py
- src/pdm/userservicedesk/HRService.py
- src/pdm/userservicedesk/TransferClientFacade.py
- test/pdm/CLI/test_usercommand.py
The single character switch is '-s' since '-p' is already used for priority. The test shows that the workqueue system is called with a correct priority='gsiftp' argument.
>  add -s/--protocol option to the CLI

- src/pdm/workqueue/WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/172
@sfayer I tried to remember what I had in last time then gave up and implemented it again. I think actually upon reflection that this new implementation is more robust and should not remove hidden files i.e. `.pylintrc`.
please test and merge.
> Remove relative dirs . and .. as gfal doesn't list them as dirs.

- src/pdm/framework/Database.py
- test/pdm/framework/test_Database.py
Hi Simon,
These are the changes to the JSON Mixin that I was talking about. Firstly since the default JSON Mixin basically made a dict of the model it now inherits from DictMixin. Secondly, you will notice that the responsibility for the encoding lies in the Mixin rather than in the encoder. This means it can be overridden by the model. Essentially the model should be responsible for how it is encoded. This will help me certainly as I won't have to maintain my own encoder.
What are your thoughts?
> Making the JSONMixin more generic.

- src/pdm/cred/CredService.py
- src/pdm/framework/Database.py
- test/pdm/framework/test_Database.py
This I think is the last piece of the puzzle. This moves the datetime formatting into the Mixin class. If you leave it in the encoder then you will get a different behaviour when using Minix.json() which won't use the encoder vs json.dumps(blah, cls=Encoder) as used in jsonify.
Again this puts full responsibility for jsonifying with the model, with JSONMixin providing the same default datetime encoding as we used to get.
> Generalise the JSONEncoder.

- src/pdm/cred/CredService.py
- src/pdm/framework/Database.py
- test/pdm/framework/test_Database.py
JSONTableEncoder can now encode standalone datetime objects again.
As an aside, I'm not convinced why we would expect the table encoder to do this anyway. The tables will already (as of my other previous new patches) encode their own datetime objects so this will only be useful for standalone datetimes. I can see that there is the convienience of having just a single encoder to maintain and use for all our jsonifying needs but maybe the naming is a bit off then. Or perhaps this should be a separate JSONDatetimeEncoder which you would use as appropriate (This would make using the same `jsonify` function difficult as you would probably have to pass along the encoder to use). 
Anyway we now (with this patch) have the best of both worlds where the tables will be responsible for encoding …
> Allowing the JSONTableEncoder to encode datetime objects as well.

- doc/source/reference/api/siteservice.rst
- src/pdm/site/SiteService.py
- test/pdm/site/test_SiteClient.py
- test/pdm/site/test_SiteService.py
As discussed earlier, this adds a CA list to the function for getting the endpoints, to make the worker coder simpler.
> Add CA listing to Site get_endpoint results

- src/pdm/utils/X509.py
- test/pdm/utils/test_X509.py
Here is the patch to add the option to pre-populate the certificates dir from another directory.
Closes #205.
> Add template_dir option to add_ca_to_dir

- src/pdm/workqueue/WorkqueueDB.py
- src/pdm/workqueue/WorkqueueService.py
- test/pdm/workqueue/test_WorkqueueService.py
This fixes https://github.com/ic-hep/pdm/issues/221
This patch also makes the http error code more explicit in cases where the updating the job element would violate the model constraint of `attempts` <= `max_tries`.
> Fix WorkqueueService to handle failing list jobs with no listing data.

- src/pdm/site/SiteService.py
- test/pdm/site/test_SiteService.py
This allows proxies to be overwritten (i.e. so that a user can login to a site a second time to renew their proxy without deleting the old one).
Closes #232.
> Fix proxy overwrite

- src/pdm/CLI/pdmcli.py
- src/pdm/CLI/user_subcommand.py
fixes #218 
In addition modify the root logger so, if a token is expired print this:
```
./src/pdm/CLI/pdmcli.py -v -c ../system.client.conf sites
Config file location used: /home/centos/Sisyphos/phase2/system.client.conf
Read config file: /home/centos/Sisyphos/phase2/system.client.conf
Token expired on 2018-05-24T01:41:16.685089
Token expired. Please log in again
```
rather than:
```
Config file location used: /home/centos/Sisyphos/phase2/system.client.conf
No handlers could be found for logger "pdm.userservicedesk.HRUtils"
Token expired. Please log in again
```
> modified logging so handlers are resolved

- src/pdm/site/SiteService.py
- test/pdm/site/test_SiteService.py
Yes, the test was mocking away the X509Utils function which normally generates a TZ aware datetime, whereas SQLAlchemy with SQLite is always TZ naive. I think the TZ from X509Utils is always GMT anyway, so just dumping the timezone fixes it. I've also updated the test case to trigger the bug, in-case of regressions :-)
Closes #232.
> Ensure cred expiry times are all naive datetimes

- src/pdm/workqueue/WorkqueueService.py
When stating relative dirs '.' and '..' gfal reports these with st_mode that evaluates as a regular file rather than a directory ie. `S_ISREG = True`, `S_ISDIR = False`. This is a quick dirty hack to explicitly exclude these dirs from COPY job expansion. It should not be necessary and when gfal is fixed we can revert this.
> Fix COPY job expansion of . and ..

- src/pdm/workqueue/WorkqueueService.py
- test/pdm/workqueue/test_WorkqueueService.py
This commit modifies the get_output function to the following specification as per our recent discussions:
* If no element_id specified get all finished elements.
* If no attempt is specified get latest attempt
main difference is that previously if element_id was omitted only the listing part of the job was returned.
> Refactor WorkqueueService.get_output.

- src/pdm/CLI/user_subcommand.py
Update job log for phase2. The default, non verbose operation lists the output of a completed job, -v dumps the whole Python structure with all job elements and attempts. Fixes #244 .
> modify the log(..) operation for phase2 jobs

- src/pdm/workqueue/Worker.py
- src/pdm/workqueue/WorkqueueClient.py
this commit also add MKDIR and RENAME jobs to the list of default worker job types and cleans up the WorkqueueClient API
> Fix to ensure that RENAME jobs have access to dst_endpoints.

- src/pdm/CLI/user_subcommand.py
Another 'long' variable left over, sorry Simon.
>  fix yet another long relataed bug

- doc/source/conf.py
This will, as the doc says, allow autodoc to document modules.
> Add src to path in Sphinx conf.py

- src/pdm/web/templates/dashboard.html
This patch also enables clicking of enter to goto a path.
fixes https://github.com/ic-hep/pdm/issues/333
fixes https://github.com/ic-hep/pdm/issues/332
> Reset botton no longer goes to ~ and path box contains non-ghosted path.

- src/pdm/web/WebPageService.py
- src/pdm/web/templates/loginform.html
The idea here is to avoid browsers auto filling them with the main login details.
fixes https://github.com/ic-hep/pdm/issues/330
> Give site login form fields different names.

- src/pdm/web/templates/joblist.html
This patch also removes the original datatables look which shouldn't be there for the bootstrap theme.
fixes https://github.com/ic-hep/pdm/issues/342
> Fix for double sorting arrows on datatables.

- src/pdm/workqueue/scripts/pdm_gfal2_ls.py
This patch filters out the '.' and '..' directories on all directory levels.
> filter . and .. directories out lin gfal_long_list()

- src/pdm/web/templates/joblist.html
- src/pdm/workqueue/WorkqueueService.py
This patch fixes https://github.com/ic-hep/pdm/issues/348
Rendering was breaking when the first listing job was subtracted before having been finished.
> Fix the rendering of progressbars.

- src/pdm/web/templates/dashboard.html
- src/pdm/web/templates/joblist.html
This fix will enforce that the directory copied ends up at the destination rather than just the content.
The need for this fix confuses me so I have left the code commented out for now. This was definitely working as @martynia and I tested all combinations. It seems that I was passing `src/src_dir` and `dst` to copy but now it needs `src/src_dir` and `dst/dst_dir`.
> Fix the paths for copying directories.

- src/pdm/workqueue/WorkqueueService.py
- test/pdm/workqueue/test_WorkqueueService.py
This fix solves the problem of directory copying into a duplicate top level dir. It also cleans up the code making it easer to read and I hope more robust.
> Workqueue copy fix

- src/pdm/workqueue/Worker.py
- src/pdm/workqueue/WorkqueueService.py
- test/pdm/workqueue/test_WorkqueueService.py
This patch fixes the failure to output correctly attempts other than the first. It also allows adding extra log information when killing the job through say timeout.
> Fix Timeout logging.

- src/pdm/web/templates/joblist.html
This PR fixes https://github.com/ic-hep/pdm/issues/405
I add the average transfer rate for running and completed jobs as long as they were running long enough to get monitoring information about them (i.e. of sufficient size)
> Add average transfer rate to the job listing page.

- src/pdm/web/templates/dashboard.html
- src/pdm/web/templates/newjob.html
This PR fixes https://github.com/ic-hep/pdm/issues/398
It also necessarily includes the sorting of endpoint listings as well as removing the border between items.
---
**Note** The setting is not remembered in a cookie yet. It may be better to open a separate issue about this if it's still desired or else will have to reopen #398 after it is auto closed
> Add visibility of hidden files toggle.
